noissue | @rebeccahongsf | add pr template
BobaTalks/mentorlist pull request #9
Opened 2022-12-07 18:16 UTC by rebeccahongsf

## Summary

- Add Github PR template

## Issue ticket number and link
- No issue

## Checklist before requesting a review
- [x] I have performed a self-review of my code

2022-12-07 18:16 UTC, rebeccahongsf commented
@jwu910 ready for review 🖖

2022-12-07 19:27 UTC, jwu910 requested changes

2022-12-07 19:27 UTC, jwu910 commented on .github/pull_request_template.md
> +- Issue #[xyz]
This could just mention and link to GitHub's linking system

They can just type a number after #

2022-12-14 00:52 UTC, jwu910 approved these changes

2022-12-14 00:52 UTC, merged